name: Development Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.gitignore'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run lint
      run: npm run lint
    
    - name: Build extension
      run: npm run build
      env:
        BUILD_SUFFIX: "-latest-dev"
    
    - name: Get version from package.json
      id: version
      run: |
        VERSION=$(node -p "require('./package.json').version")
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Building version $VERSION"
    
    - name: Get previous release tag
      id: prev_version
      run: |
        # Get the latest release tag (excluding latest-dev)
        PREV_TAG=$(git tag -l 'release-*' | sort -V | tail -1)
        
        if [ -n "$PREV_TAG" ]; then
          echo "prev_tag=$PREV_TAG" >> $GITHUB_OUTPUT
          echo "Previous release tag: $PREV_TAG"
        else
          echo "ERROR: No previous release tags found"
          exit 1
        fi
    
    - name: Delete existing Latest Development Release
      uses: dev-drprasad/delete-tag-and-release@v1.0
      with:
        tag_name: latest-dev
        github_token: ${{ secrets.GITHUB_TOKEN }}
        delete_release: true
      continue-on-error: true
    
    - name: Create Latest Development Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: latest-dev
        release_name: Latest Development Build (${{ steps.version.outputs.version }})
        body: |
          This is an automated development build from the latest commit on the main branch.
          
          ### Important Notes:
          - This is a development build and may contain unstable features, but also the latest fixes
          - This release is automatically updated with each push to the main branch
          - For release versions, see the [releases page](https://github.com/crybx/Grabby/releases)
          
          ### Chrome Installation:
          1. Download the ZIP file below
          2. Extract the ZIP file  
          3. Open chrome://extensions/
          4. Enable "Developer mode"
          5. Click "Load unpacked" and select the extracted folder
          
          ### Full Changelog: 
          [${{ steps.prev_version.outputs.prev_tag }}...latest-dev](https://github.com/crybx/Grabby/compare/${{ steps.prev_version.outputs.prev_tag }}...latest-dev)
        draft: false
        prerelease: true
    
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./grabby-${{ steps.version.outputs.version }}-latest-dev.zip
        asset_name: grabby-${{ steps.version.outputs.version }}-latest-dev.zip
        asset_content_type: application/zip
    
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: grabby-latest-dev-${{ steps.version.outputs.version }}
        path: grabby-${{ steps.version.outputs.version }}-latest-dev.zip
        retention-days: 3